plugins { id 'com.android.application' }

android {
    namespace 'ca.lotkeys.connector'
    compileSdk 35

    defaultConfig {
        applicationId 'ca.lotkeys.connector.test'
        minSdk 30
        targetSdk 35
        versionCode 9487
        versionName '0.9.4.87-test'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        warningsAsErrors false
        disable 'BatteryLife'
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
